[project]
dependencies = [
  "cython>=3.2.4",
]
description = "Algorithm implemented by JS/TS/C++/Python"
name = "algorithm"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[dependency-groups]
dev = [
  "ruff>=0.14.3",
]
